" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible


" https://tlvince.com/vim-respect-xdg
" Environment
set directory=$XDG_CACHE_HOME/vim,~/,/tmp
set backupdir=$XDG_CACHE_HOME/vim,~/,/tmp
set viminfo+=n$XDG_CACHE_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIM,$VIMRUNTIME
let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"


" when the terminal has colors
if &t_Co > 2 || has("gui_running")
    source $XDG_CONFIG_HOME/vim/subrcs/color-dependent
endif


" Autocommands are a way to tell Vim to run certain commands
" whenever certain events happen. Let's dive right into an example.
if has("autocmd")
    source $XDG_CONFIG_HOME/vim/subrcs/autocmd
else
  " always set autoindenting on
  set autoindent
endif


source $XDG_CONFIG_HOME/vim/subrcs/ext-filetype


" support embedded vim settings in file
set modeline


" set numbers
set nu
" set relative numbers
set rnu


set noexpandtab
set copyindent
set preserveindent
set softtabstop=0
set shiftwidth=4
set tabstop=4

" set fileformats=unix,dos

" Save feature
nmap <F2> :w<CR>
imap <F2> <ESC>:w<CR>i<Right>
nmap <F10> :wq<CR>
imap <F10> <ESC>:wq<CR>

" Toggle wrap.
nmap <leader><leader>w :set wrap! wrap?<cr>
" <F9> toggles word wrap
" map  <F9> :set wrap!<CR>
" imap <F9> <ESC>:set wrap!<CR>a

" http://vi-improved.org/vimrc.html
