#!/usr/bin/env bash

# https://itnext.io/using-git-hooks-to-enforce-branch-naming-policy-ffd81fa01e5e

valid_branch_regex="^[0-9A-Za-z_\-\/]+$"

git rev-parse --abbrev-ref HEAD | grep -Eq "${valid_branch_regex}"

if [ $? -ne 0 ]
then
    echo "Allowed chars for branch name are next: $valid_branch_regex"
    exit 1
fi

exit 0

