#!/usr/bin/env bash

# ASYNC TASKS

if [ -f ~/.bin/logout_tasks_async ]; then
    (nohup ~/.bin/logout_tasks_async >/dev/null 2>&1 &) >/dev/null 2>&1
fi


# SYNC TASKS

if [ -f ~/.bin/logout_tasks_sync ]; then
    ~/.bin/logout_tasks_sync
fi

